<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Actividad extends Model
{
    protected $fillable = [
        'name',
        'dia_semana',
        'hora_inicio',
        'hora_fin',
    ];

    public function actividadanimal()
    {
        return $this->belongsTo('App\Models\ActividadAnimal');
    }
}
