<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'name',
        'especie_id',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie');
    }

    public function cuidadoranimal()
    {
        return $this->belongsTo('App\Models\CuidadorAnimal');
    }

    public function actividadanimal()
    {
        return $this->belongsTo('App\Models\ActividadAnimal');
    }

    public function animalrecinto()
    {
        return $this->belongsTo('App\Models\AnimalRecinto');
    }
}
