<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Cuidador extends Model
{
    protected $fillable = [
        'name',
        'descripcion',
    ];

    public function cuidadoranimal()
    {
        return $this->belongsTo('App\Models\CuidadorAnimal');
    }
}
